apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markerworld-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: markerworld-svc
            port:
              number: {{ .Values.service.port }}