env:
  APP_NAME: 'markerworld'

name: PR-Env
 
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
         fetch-depth: 0
         
      - name: Bump version and push tag
        id: bumpver
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          
      - name: bumpver output
        run: echo ${{ steps.bumpver.outputs.new_tag }} ${{ steps.bumpver.outputs.tag }} ${{ steps.bumpver.outputs.part }}
        
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: nfler/${{ env.APP_NAME }}
          tags: |
           type=semver,pattern={{version}},value=${{ steps.bumpver.outputs.new_tag }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev

      - name: Setup namespace
        run: kubectl create namespace ${{ env.APP_NAME }}-pr-${{ github.event.number }} --dry-run=true -o yaml | kubectl apply -f -

      - name: Create jwt auth secret
        run: kubectl create secret -n ${{ env.APP_NAME }}-pr-${{ github.event.number }} generic jwt-auth-secret --from-literal=JWT_AUTH_SECRET=${{ secrets.PR_ENV_JWT_AUTH_SECRET }}
      
      - name: Create jwt refresh secret
        run: kubectl create secret -n ${{ env.APP_NAME }}-pr-${{ github.event.number }} generic jwt-refresh-secret --from-literal=JWT_REFRESH_SECRET=${{ secrets.PR_ENV_JWT_REFRESH_SECRET }}

      - uses: azure/setup-helm@v1

      - name: Deploy with helm
        run: helm upgrade --set environment=prenv --set image.tag=${{ steps.meta.outputs.version }} --set pr=${{ github.event.number }} ${{ env.APP_NAME }}-pr-${{ github.event.number }} ./chart -i -n ${{ env.APP_NAME }}-pr-${{ github.event.number }}

