name: PR-Env
 
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout code
        
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: nfler/markerworld
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}

      - name: Echo image tag
        run: echo nfler/markerworld:${{ steps.meta.outputs.tags }}
        
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev
      
      - uses: azure/setup-helm@v1

      - name: Deploy with helm
        run: helm upgrade --set image.tag=${{  steps.meta.outputs.tagss }} --set ingress.host=api.pr-${{ github.event.number }}.nfler.se markerworld-pr-${{ github.event.number }}- ./markerworld-chart -i --create-namespace -n markerworld-pr-${{ github.event.number }}


